config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :new, :create, :edit, :update]
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  accepts_nested_attributes_for :ingredients, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def edit
    @recipe = Recipe.find params[:id]
  end

  def update
    @recipe = Recipe.find params[:id]

    if @recipe.update recipe_params
      redirect_to recipes_url
    else
      render :edit
    end
  end

  def new
    @recipe = Recipe.new
    4.times { @recipe.ingredients.build }
  end

  def create
    @recipe = Recipe.new recipe_params
    
    if @recipe.save
      redirect_to recipes_url
    else
      render :new
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, ingredients_attributes: [:id, :name, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipesBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= nested_form_for @recipe do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <h4>Ingrediencie</h4>
  
  <%= f.fields_for :ingredients do |ingredient| %>
    <%= ingredient.text_field :name %>
    <%= ingredient.link_to_remove "Odstranit ingredienciu" %>
    <br>
  <% end %>
  <%= f.link_to_add "Pridat ingredienciu", :ingredients %>

  <p><%= f.submit %></p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Upraviť recept</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>Recepty</h1>

<% @recipes.each do |recipe| %>
  <p>
    <strong><%= recipe.name %></strong>
    
    <br>
    Ingrediencie:
    <%= recipe.ingredients.map{|i| i.name}.join(", ") %>

    <br>
    <%= link_to "Upraviť recept", edit_recipe_path(recipe) %>
  </p>
<% end %>

app/views/recipes/new.html.erb
<h1>Pridat recept</h1>

<%= render 'form' %>